DROP TABLE LIBRO;
DROP TABLE ESTANTERIA;

CREATE TABLE ESTANTERIA (
    ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    PRIMARY KEY(ID),
    NOMBRE VARCHAR(20)
);

INSERT INTO ESTANTERIA(NOMBRE) VALUES
    ('Fondo'), 
    ('Detrás-Escritorio'),
    ('Escalera');

CREATE TABLE LIBRO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NOMBRE VARCHAR(50) NOT NULL,
    AUTOR VARCHAR(50) NOT NULL,
    UBICACION INTEGER NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(UBICACION) REFERENCES ESTANTERIA
);

INSERT INTO LIBRO(NOMBRE, AUTOR, UBICACION) VALUES
    ('Libro 1.1', 'Autor 1', 0),
    ('Libro 1.2', 'Autor 1', 1),
    ('Libro 1.3', 'Autor 1', 1),
    ('Libro 2.1', 'Autor 2', 2),
    ('Libro 2.2', 'Autor 2', 2);